SERVER_IP = '127.0.0.1'
SERVER_PORT = 20000
BUFFER_SIZE = 1024

CONNECTION_REQUEST = 'connection_request'
CONNECTION_FINISHED = 'connection_finished'
REQUEST_TO_SEND = 'request_to_send'

COMMANDS = [
    CONNECTION_FINISHED,
    CONNECTION_REQUEST,
    REQUEST_TO_SEND
]
